### ISSUE TITLE
Add unit test to check if quotes have desired formats.

### ISSUE THREAD

**Issue by NikhilNamal17** [NikhilNamal17/popular-movie-quotes#201]
Add mocha unit tests to check if quotes have desired formats.
 
```js
{  
      "quote": "String",
      "movie": "String",
      "type": "String",
      "year": Number
}
```

The test should check if the quote exists and is a type of String, same goes with each attribute with an associated data type.

**Comment by Laviitz** [comment]
I would like to do that. Can you assign this issue for me?

**Comment by NikhilNamal17** [comment]
@Laviitz fixed this issue, just need some small changes.
