### ISSUE TITLE
Add more movie quotes

### ISSUE THREAD

**Issue by NikhilNamal17** [NikhilNamal17/popular-movie-quotes#3]
Do you know any popular movie quotes?
Add your quote to data.json inside the data/ folder and raise the PR.
Language: Only English

```json
{  
      "quote": "Your new Quote",
      "movie": "movie name",
      "type": "movie/anime/tv",
      "year": 2012
}
```

Note:

Please avoid the repetition of quotes. 
Add your quotes in between. Don't add at the bottom or at the top.
Follow the template. 
Do not make any changes in other files.
Add me(@NikhilNamal17 ) as reviewer.
Thanks!

**Comment by robflop** [comment]
Hello, I have a question. Does "first-timers-only" (and its hovertext "Send your first PR") refer to one's first Hacktoberfest PR or how is this to be understood?

**Comment by NikhilNamal17** [comment]
The label refers to their first open-source contribution. Basically this issue is targeted for beginners but there are no restrictions.

**Comment by robflop** [comment]
Okay, thank you. If multiple PRs can be accepted for this issue then I would like to submit one. If not I will leave it for someone that is a beginner.

**Comment by jdim** [comment]
Hi, can I help? It's funny))

**Comment by NikhilNamal17** [comment]
@robflop Yes, you can send multiple PR.

**Comment by DylPickle11** [comment]
Ok I will also do that! YAY!

**Comment by bigton54** [comment]
I would like to add some!

**Comment by k1dnyy** [comment]
I would love to add a few!

**Comment by MSurfer20** [comment]
Can I contribute?

**Comment by rvk7895** [comment]
I would like to contribute to this.TIA

**Comment by Harshwp** [comment]
I would love to contribute

**Comment by NikhilNamal17** [comment]
@MSurfer20 sure.

**Comment by jaywantpatel** [comment]
Can I contribute to this ?

**Comment by NikhilNamal17** [comment]
@jaywantpatel sure.

**Comment by davidlfox** [comment]
How can I test this locally before submitting PR?

**Comment by davidlfox** [comment]
> How can I test this locally before submitting PR?

from project directory
```
cd ..
mkdir popular-movie-quotes-test
cd popular-movie-quotes-test
npm install ../popular-movie-quotes
npm install requirejs
cp ../popular-movie-quotes/demo/demo.js .
node demo.js
```

**Comment by Babadzhanov** [comment]
added #77

**Comment by ShivashMahespalsingh** [comment]
Are Indian movie quotes also allowed?

**Comment by NikhilNamal17** [comment]
> Are Indian movie quotes also allowed?

@ShivashMahespalsingh currently only English movies.

**Comment by davidlfox** [comment]
> > Are Indian movie quotes also allowed?
> 
> @ShivashMahespalsingh currently only English movies.

You might consider adding expectations like this to either the issue or maybe even the readme

**Comment by dominikS007** [comment]
Can I contribute ?

**Comment by rajk1121** [comment]
I want to add a quote.

**Comment by anshuldutt21** [comment]
Hi, I want to contribute

**Comment by colis123** [comment]
Hello. Id like to add some

**Comment by dtoledoz0207** [comment]
Hi, I would like to contribute

**Comment by ShivashMahespalsingh** [comment]
I see a that lot of the JSON objects in the data.json files have different formats. Most of them have the "type" property missing is this an issue?

**Comment by NikhilNamal17** [comment]
> I see a that lot of the JSON objects in the data.json files have different formats. Most of them have the "type" property missing is this an issue? Or does the code expect this kind of input?

@ShivashMahespalsingh that objects with parameter missing are old data, in beginning we didn't asked for type and year, we updated the template but then it was too much data, adding manually was impossible.

**Comment by NikhilNamal17** [comment]
Also, I cleared all duplicates quotes too. Now it's around 1k lines. It would be great if someone can review and add missing attributes,

**Comment by ShivashMahespalsingh** [comment]
> Also, I cleared all duplicates quotes too. Now it's around 1k lines. It would be great if someone can review and add missing attributes,

I will review the objects and create a pull request after adding the missing attributes.

**Comment by Somrajkarki** [comment]
Hi, can i contribute?

**Comment by piyushs2894** [comment]
Hi Nikhil, I have created a new PR for new quote. Can u please check it?
https://github.com/NikhilNamal17/popular-movie-quotes/pull/139

**Comment by anshgit101** [comment]
i am submitting pr with my contribution to the movie quotes please review

**Comment by anshuldutt21** [comment]
https://github.com/NikhilNamal17/popular-movie-quotes/pull/164#issue-326222966

**Comment by anshuldutt21** [comment]
Added movie quotes #164

**Comment by prosaicpudding** [comment]
What a fun way to build a dataset. I will add some as well.

**Comment by prosaicpudding** [comment]
I found a duplicate quote. Would it be okay for me to remove it, or should I leave it alone?

**Comment by darpanjbora** [comment]
> Also, I cleared all duplicates quotes too. Now it's around 1k lines. It would be great if someone can review and add missing attributes,

I have created a new issue for the same. #210  
I have added the missing attribute "type" to all the objects. Submitted PR #211 
Kindly review and accept the PR.
Also adding the script that I had used for reference. 

> const data = require("../data/data.json");
const fs = require('fs');
var new_data = data.map( datum => {
    var newField = Object.assign({}, datum);
    newField.type = "movie";
    return newField;
})
fs.writeFileSync('file.json', JSON.stringify(new_data));

**Comment by prosaicpudding** [comment]
I've noticed a few quotes that are misattributed. Would correcting that fall under this issue as well?

**Comment by tylercaceres** [comment]
I would like to contribute. :)

**Comment by iepoch** [comment]
I would like to work on this as well! :)

**Comment by Kudzanayi-Dzvairo** [comment]
How do I add you as a reviewer?

**Comment by Volence** [comment]
Just did my first pull request on github! I'm used to gitlab so please let me know if I did anything incorrectly. I tagged you in that but I'm not sure if that made you the reviewer. Thanks for this project!

**Comment by mai-am** [comment]
Added a few from Once Upon a Time in Hollywood. Couldn't figure out how to make you the reviewer @NikhilNamal17. :)

**Comment by aisayo** [comment]
Hi, added a new quote however could not figure out how to make you the reviewer

**Comment by urielkdev** [comment]
Is there any reason to have repeated quotes? If not, can I remove them?

**Comment by NikhilNamal17** [comment]
@urielkdev I already wrote tests to clean up.

**Comment by raksh07** [comment]
I would like to work on this

**Comment by georgerodriguex** [comment]
#321 here

**Comment by ShivamS136** [comment]
#330 
Another Iconic Dialogue from the Iconic Character - JOKER
Please accept the PR

**Comment by SaundraMJohnson** [comment]
Added Love and Basketball movie quote SHA-#f890ffa

**Comment by SaundraMJohnson** [comment]
added Love and Basketball quote #372, requesting a merge. Thank you.

**Comment by SaundraMJohnson** [comment]
Added one more quote from 300. #373, requesting merge. Thank you for maintaining.

**Comment by ryuakaa** [comment]
Added a new quote #386
added some spaces for styling purposes :wink:

**Comment by skathuria29** [comment]
Added a new movie quote #394

**Comment by alam3211** [comment]
Hi, let me add some of my favorite movie quotes #399

**Comment by alangordon** [comment]
Added a quote #412

**Comment by vchandev** [comment]
Hi, I would like to add some quotes too

**Comment by CodeMeKathy** [comment]
Hi! I would like to contribute and add some additional quotes as well.

**Comment by pgvr** [comment]
I added a quote too 👍 #440

**Comment by deinakings** [comment]
Added a new quote! https://github.com/NikhilNamal17/popular-movie-quotes/pull/446

**Comment by vpettit** [comment]
I added some quotes! https://github.com/NikhilNamal17/popular-movie-quotes/pull/463

**Comment by reybilla** [comment]
Added https://github.com/NikhilNamal17/popular-movie-quotes/pull/468

**Comment by darkdraiden14** [comment]
Added #509
